services:
  build:
    build:
      context: .
    environment:
      - LIBEVENT_VERSION=2.1.12-stable
      - NCURSES_VERSION=6.5
      - TMUX_VERSION=3.4
    volumes:
      - cache:/opt/archive
      - ./output:/opt/output:rw
      - ./prefix:/opt/prefix:rw

volumes:
  cache:
